### ISSUE TITLE
show() DimEstimate that has empty units 

### ISSUE THREAD

**Issue by b-r-hamilton** [ggebbie/BLUEs.jl#41]
I'm trying to do a `solve` for a problem with units, and the output has dimensions, but not units. To be able to multiply this by elements with units, I've been assigning it NoUnit units. However, this is throwing an error related to the `getproperty`
Here's a MWE 
```
using BLUEs, Unitful, DimensionalData, UnitfulLinearAlgebra, LinearAlgebra
using Revise
K = u"K"

#unitless DE works 
de1 = DimEstimate(rand(25), rand(25, 25), (X(1:5), Y(1:5)))

#unitful DE works 
urange2 = fill(K, 25)
y2 = UnitfulMatrix(rand(25), urange2)
Cyy2 = UnitfulMatrix(rand(25,25), urange2, urange2 .^ -1)
de2 = DimEstimate(y2, Cyy2, (X(1:5), Y(1:5)))

#what if the type is a Quantity but no units
urange3 = fill(NoUnits, 25)
y3 = UnitfulMatrix(rand(25), urange3)
Cyy3 = UnitfulMatrix(rand(25, 25), urange3, urange3 .^ -1)
#next line technically runs, but fails the show
de3 = DimEstimate(y3, Cyy3, (X(1:5), Y(1:5)))
```
The error looks like 
```
julia> de3 = DimEstimate(y3, Cyy3, (X(1:5), Y(1:5)))
DimEstimate{Float64, Float64}
Estimate and 1σ uncertainty
Error showing value of type DimEstimate{Float64, Float64}:
ERROR: MethodError: no method matching measurement(::Quantity{Float64, NoDims, Unitful.FreeUnits{(), NoDims, nothing}}, ::Float64)
```
I think I've tracked the problem to the fact that `de3.v` and `de2.v` both return UnitfulMatrix, but `de3.\sigma` returns `Vector{Float}` while `de2.v` returns a `Vector{Quantity}`. This causes the above error at Line 154 
https://github.com/ggebbie/BLUEs.jl/blob/d94ed006eb5580e44715c843b69ab9a55bda2b3b/src/BLUEs.jl#L154C22-L154C22
When `measurement.` is called in `getproperty`, it's receiving a Quantity for the `v` value and a Float for `x.\sigma`, hence the above error. 

After a little perusing, I've come up with two solutions 
1. Hacky solution in `getproperty`: just check the actual units on `x.v` and if they're NoUnits, call `parent`. This would just look like changing the following line 
https://github.com/ggebbie/BLUEs.jl/blob/d94ed006eb5580e44715c843b69ab9a55bda2b3b/src/BLUEs.jl#L150
to 
```
v = x.v.dims[1][1] isa Unitful.FreeUnits{(), NoDims, nothing} ? parent(x.v) : Matrix(x.v)
```
2. Less hacky, more likely to break something else: the real root of the problem is that `x.\sigma` should not return `Vector{Float}`, it should return `Vector{Quantity}`. This type gets decided by `diag(x.C)` in `getproperty`. `diag` first checks `dimensionless(x.C)` which returns true for the case where the dimensions are NoUnits. I guess this is technically correct, but ultimately causes `diag` to return the `Vector{Float}`. Should there be a third case in `diag` for the UnitfulMatrix with NoUnits? Or should `dimensionless` return `false` for this case? (I guess I don't really have a solution here, but more questions)

**Comment by ggebbie** [comment]
2 is more consistent with `UnitfulLinearAlgebra`. Add third case to `diag`?

**Comment by b-r-hamilton** [comment]
I think this may have broken again... Following doesn't work for me. Not quite sure what happened yet :/ 
```
julia> using UnitfulLinearAlgebra, Unitful, BLUEs

julia> de = DimEstimate(rand(5)u"permille", rand(5,5)u"permille", (5,5))
DimEstimate{Quantity{Float64, NoDims, Unitful.FreeUnits{(‰,), NoDims, nothing}}, Quantity{Float64, NoDims, Unitful.FreeUnits{(‰,), NoDims, nothing}}}
Estimate and 1σ uncertainty
Error showing value of type DimEstimate{Quantity{Float64, NoDims, Unitful.FreeUnits{(‰,), NoDims, nothing}}, Quantity{Float64, NoDims, Unitful.FreeUnits{(‰,), NoDims, nothing}}}:
ERROR: MethodError: no method matching size(::Tuple{Int64, Int64})

```
Seems like it's coming back to an issue with `diag` again.

**Comment by b-r-hamilton** [comment]
Ok, how about this - extend UnitfulLinearAlgebra.diag so that it can act upon a DImEstimate or Estimate, and then just write a probably less efficient (but still pretty fast for me) version that just uses `getindexqty`. 
See changes in branch #41bdimestimateshow

**Comment by ggebbie** [comment]
I can reproduce your error.

However I can get this to work:
```de = DimEstimate(rand(25)u"K", rand(25,25)u"K^2", (X(1:5),Y(1:5)))```

I had to change the units of the covariance matrix, the dimension of the estimate, and use X and Y.

It also works with permille
```de = DimEstimate(rand(25)u"permille", rand(25,25)u"permille^2", (X(1:5),Y(1:5)))```

**Comment by b-r-hamilton** [comment]
Hmm, you're right. Bad attempt to write a MWE on my part. I'm running into this issue when trying to multiple a DimEstimate by a UnitfulMatrix (propagating a solution through the model matrix), and I thought this was the issue, but this makes it seem like it's something going on with the multiplication. Let me take a deeper look and try and figure out what's going on.

**Comment by b-r-hamilton** [comment]
(mainly leaving this as a note for myself for when I run into this again) 

Okay, I think the error seems to be stemming from defining a DimEstimate using a UnitfulMatrix that is in units of permlle. 
```
julia> de = DimEstimate(UnitfulMatrix(rand(25)u"K"), UnitfulMatrix(rand(25,25)u"K^2"), (X(1:5),Y(1:5)))
DimEstimate{Float64, Float64}
Estimate and 1σ uncertainty
5×5 DimArray{Quantity{Measurements.Measurement{Float64}, 𝚯, Unitful.FreeUnits{(K,), 𝚯, nothing}},2} with dimensions: 
  X Sampled{Int64} 1:5 ForwardOrdered Regular Points,
  Y Sampled{Int64} 1:5 ForwardOrdered Regular Points
              1             2             3              4             5
 1   0.5±0.57 K  0.012±0.18 K     0.5±0.5 K    0.49±0.23 K    0.7±0.92 K
 2  0.78±0.93 K   0.56±0.25 K   0.54±0.75 K    0.58±0.88 K   0.38±0.44 K
 3  0.89±0.88 K   0.34±0.69 K  0.337±0.09 K    0.44±0.82 K   0.039±0.9 K
 4  0.78±0.65 K   0.31±0.63 K   0.42±0.17 K  0.0028±0.84 K  0.013±0.21 K
 5  0.27±0.63 K    0.5±0.89 K   0.52±0.52 K    0.97±0.68 K    0.5±0.91 K

julia> de = DimEstimate(UnitfulMatrix(rand(25)u"permille"), UnitfulMatrix(rand(25,25)u"permille^2"), (X(1:5),Y(1:5)))
DimEstimate{Float64, Float64}
Estimate and 1σ uncertainty
Error showing value of type DimEstimate{Float64, Float64}:
```
I can work around this by just computing the multiplication myself, casting to Matrix, and then making my own DimEstimate. 
So I don't think any fix is required. Can ignore the 41b branch
