### ISSUE TITLE
runtests breaks due to UnitfulLinearAlgebra.ldiv problem

### ISSUE THREAD

**Issue by b-r-hamilton** [ggebbie/BLUEs.jl#50]
I have an error being thrown on #47 right now that also occurs is if I clone a fresh version of BLUEs, and run `runtests.jl` again. The error is that for any `\`, a `DimensionMismatch` occurs. Not quite sure why this is happening... 

Example error 

```
julia> include("test/runtests.jl")
left-uniform problem with prior info: Error During Test at /home/brynn/Downloads/BLUEs.jl/test/runtests.jl:89
  Got exception outside of a @test
  DimensionMismatch: Dimension index [‰] and Unitful.FreeUnits[‰] do not match
  Stacktrace:
```

**Comment by ggebbie** [comment]
upstream (UnitfulLinearAlgebra) problem. Sorry that a recent PR broke your code for `FixedUnits`. Must come from this PR https://github.com/ggebbie/UnitfulLinearAlgebra.jl/pull/94 .
